#USERSERVICE'S CONFIG


server:
  port: 0
spring:
  application:
    name: userService
    datasource:
      url: jdbc:postgresql://revature.cz2dcuuxy0ge.us-west-2.rds.amazonaws.com/p3UserService
    password: p4ssw0rd
    username: adminuser
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
          jdbc:
            lob:
              non_contextual_creation: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id:  ${spring.application.name}:${random.value}
    preferIpAddress: true
